spring:
    profiles:
        active: dev
        include: secret
    jpa:
        hibernate:
            ddl-auto: create # 애플리케이션 실행시 DB테이블을 자동으로 생성함.
        # 기존 데이터는 삭제되고 새로 테이블이 만들어짐-개발환경에서 주로 사용됨.
        properties:
            hibernate:
                show_sql: true # 실행되는 SQL쿼리를 콘솔에 출력.
                format_sql: true #SQL 출력시 보기 좋게 들여쓰기/정렬
                use_sql_comments: true # SQL 로그에 주석을 포함

logging:
    level:
        root: INFO # 전체 애플리케이션의 로그 레벨을 INFO로 설정
                    # DEBUG나 TRACE는 더 상세한 로그,
                    # ERROR는 최소한의 로그만 출력
