## 개발용
server:
    port: 8080
spring:
    output:
        ansi:
            enabled: always
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://3.39.177.130:3306/my_db
        username: root
        password: 1111
custom:
    fileDirPath: /usr/work